twilio:
  development: &default
    account_sid: <%= ENV['TWILIO_ACCOUNT_SID'] %>
    auth_token: <%= ENV['TWILIO_AUTH_TOKEN'] %>
    forwarding_number: <%= ENV['FORWARDING_NUMBER'] %>
    recipient_number: <%= ENV['RECIPIENT_NUMBER'] %>

  test:
    <<: *default

  production:
    <<: *default
